### ISSUE TITLE
Taal

### ISSUE THREAD

**Issue by RutgerBos** [RutgerBos/PECAN#3]
Moeten nog even beslissen welke taal we het in willen schrijven. Misschien iets voorbarig, maar dan kunnen we iig het op een centraal punt bespreken.

Dingen die we sowieso willen:
- cross-platform
- Libraries voor crossplatform GUI bullshit bestaat, niet heel veel zin om zelf een complete graphics library in elkaar te moeten flanzen.
- Parallelisering wordt goed ondersteund
- Snel

C/C++ blijft hierdoor een decent contender, denk ik, hoewel we dan wel nog wat moeten vinden voor het paralleliseren.

**Comment by gijsschroder** [comment]
Voorlopig beschouw ik dit repo vooral als communicatiemiddel om onderzoek te ondersteunen. Taal lijkt me daarom nu vooral een kwestie van wat makkelijk communiceert. Verder:

* Is er een taal die voor ons beiden makkelijk is om in te prototyperen en om te lezen? Mijn C# ervaring houdt op bij het lezen van een boek erover heel heel lang geleden.
* C++ is een mooie middenweg tussen goed ondersteund, snel en conventioneel. Presentatie (dus GUI) is voorlopig geen zorg; wanneer een bibliotheek bestaat die de simulatie uitvoert kan er een frontend geschreven worden die geproduceerde gegevens inspecteert en toont.
* Ik geef hele grote voorkeur aan coderen in het Engels.

**Comment by RutgerBos** [comment]
> C++ is een mooie middenweg tussen goed ondersteund, snel en conventioneel. Presentatie (dus GUI) is voorlopig geen zorg; wanneer een bibliotheek bestaat die de simulatie uitvoert kan er een frontend geschreven worden die geproduceerde gegevens inspecteert en toont.

Ja, klinkt als een plan.

> Voorlopig beschouw ik dit repo vooral als communicatiemiddel om onderzoek te ondersteunen. 
Idem. Ik had iets gepushed, maar ik kan het niet vinden. Zal nog even kijken naar wat er daar gebeurt is.

> Ik geef hele grote voorkeur aan coderen in het Engels.

Ik geef zelf de voorkeur aan Frans, maar omdat ik die taal niet spreek vind ik het best om het in het engels te doen. :^)

**Comment by RutgerBos** [comment]
C# voor nu. Door gebruik van CLI kunnen we later alsnog een keer overstappen naar wat anders zonder dat er van buitenaf heel veel van moet worden gemerkt.
